--- 
VA: Visual Arts
APA: Advancement of Public Action
JPN: Japanese
CS: Computer Science
PSY: Psychology
MUS: Music
SCMA: Science and Math
MAT: Mathematics
ITA: Italian
EDU: Education; Center for Creative Teaching
CHE: Chemistry
PHY: Physics
PHO: Photography
MTH: Music Theory
MSR: Music Sound Design and Recording
MED: Mediation
LIT: Literature
POL: Politics and International Relations
PAI: Painting
MOD: Modules
ENV: Environmental Studies
PEC: Political Economy
MPF: Music Performance
MHI: Music History
MCO: Music Composition
FRE: French
ES: Earth Sciences
SPA: Spanish
CHI: Chinese
SCU: Sculpture
FV: Film and Video
CER: Ceramics
PHI: Philosophy
MVO: Music Voice
DAN: Dance
PRI: Printmaking
MIN: Music Instrumental Study
HIS: History
DA: Digital Arts
ARC: Architecture
ANT: Anthropology
AH: Art History
DRA: Drama
DL: Design Lab
BIO: Biology
MA: Media Arts
FLE: Foreign Language Education
DRW: Drawing
MFN: Music Fundamentals
